### ISSUE TITLE
WebSocket not present in global scope and no wsConstructor option was provided

### ISSUE THREAD

**Issue by Mehranh** [blocknative/notify#179]
Hi

I installed bnc-notify 1.5.0 in my NodeJs app,
It took an error that you can see below on initial line.

`notify = Notify(options);
`
```
Error: WebSocket not present in global scope and no wsConstructor option was provided.
    at new SturdyWebSocket (D:\Source\CryptomindWallet\node_modules\bnc-notify\dist\notify.umd.js:534:1363)
    at new Blocknative (D:\Source\CryptomindWallet\node_modules\bnc-notify\dist\notify.umd.js:2305:4758)
    at init$1 (D:\Source\CryptomindWallet\node_modules\bnc-notify\dist\notify.umd.js:3650:2274)
``
```

Could you please help us to resolve this?

Thanks

**Comment by aaronbarnardsound** [comment]
Hey @Mehranh Notify.js is for transaction notifications and will not work in the browser. If you are looking for transaction events in a node.js instance, check out our [SDK](https://github.com/blocknative/sdk). Also [check out the docs](https://docs.blocknative.com/notify-sdk#initialize-the-library) as a WebSocket constructor needs to be passed in to work in node.js.
